SELECT LASTNAME,
       SALARY,
       BONUS
FROM EMPLOYEE 
WHERE SEX = 'M';

SELECT LASTNAME,
       SALARY,
       COMM
FROM EMPLOYEE
WHERE SALARY > 20000.00
and HIREDATE >= '1980-01-01';

SELECT LASTNAME, 
       SALARY, 
       BONUS, 
       COMM
FROM EMPLOYEE
WHERE SALARY > 22000.00
      AND BONUS IN (400, 500)
      AND COMM < 1900
ORDER BY LASTNAME;

SELECT PROJNO,
       ACTNO,
       EMSTDATE,
       EMENDATE
FROM EMPPROJACT
WHERE REGEXP_LIKE (PROJNO, '^AD[0-9]+$' )
      AND ACTNO IN(10,80,180)
ORDER BY PROJNO, ACTNO;

SELECT LASTNAME,
       FIRSTNME,
       D.DEPTNAME
FROM EMPLOYEE AS E 
     INNER JOIN DEPARTMENT AS D ON E.WORKDEPT = D.DEPTNO
ORDER BY D.DEPTNAME, LASTNAME, FIRSTNME;

SELECT LASTNAME, 
       FIRSTNME,
       D.DEPTNAME,
       JOB
FROM EMPLOYEE AS E 
     INNER JOIN DEPARTMENT AS D ON E.WORKDEPT = D.DEPTNO
WHERE E.WORKDEPT BETWEEN 'A02'and 'D22'
      and JOB != 'MANAGER'
ORDER BY D.DEPTNAME, JOB, LASTNAME, FIRSTNME;

SELECT DISTINCT P.PROJNO, 
       P.PROJNAME,
       PA.ACTNO
FROM PROJECT AS P 
     INNER JOIN PROJACT AS PA USING(PROJNO)
WHERE REGEXP_LIKE (P.PROJNO, '^AD[0-9]+$' )
ORDER BY P.PROJNO, PA.ACTNO;

SELECT E.WORKDEPT AS DEPTNO,
       M.LASTNAME AS MANAGER,
       E.LASTNAME AS  EMPLOYEE,
       M.HIREDATE AS M_HIREDATE,
       E.HIREDATE AS E_HIREDATE
FROM EMPLOYEE AS E,
     (SELECT LASTNAME, HIREDATE
      FROM EMPLOYEE AS E 
           INNER JOIN DEPARTMENT AS D ON E.WORKDEPT = D.DEPTNO 
      WHERE E.EMPNO = D.MGRNO and E.WORKDEPT = 'A00') AS M
WHERE E.WORKDEPT = 'A00' AND  M.HIREDATE > E.HIREDATE
ORDER BY E.LASTNAME;
