---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secretapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-secret-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-secret-app
    spec:
      containers:
        - image: nginx:1.17
          name: nginx
          ports:
          - containerPort: 80
          volumeMounts:
            - mountPath: /opt/default-secret.yaml
              name: secret-conf-volume  
      volumes:
        - name: secret-conf-volume
          configMap:
            name: pass-conf
      
  
